from __future__ import annotations

import json
import stat
import subprocess
from pathlib import Path

import pytest

from bester_ytm.auth_capture import (
    build_headers_raw,
    cookie_header_from_netscape,
    detect_browsers,
    ensure_required_headers,
    export_browser_cookie_header,
    headers_from_paste,
)
from bester_ytm.config import ConfigError

NETSCAPE_COOKIES = """\
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com\tTRUE\t/\tTRUE\t0\tSAPISID\tsap-value
.youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-3PAPISID\tsap-value
#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-3PSID\tsession-value
.example.com\tTRUE\t/\tFALSE\t0\tOTHER\tother-value
"""


def _write_cookies(path: Path, content: str = NETSCAPE_COOKIES) -> Path:
    path.write_text(content, encoding="utf-8")
    return path


def test_detect_browsers_orders_firefox_first(tmp_path: Path) -> None:
    (tmp_path / ".config" / "chromium").mkdir(parents=True)
    (tmp_path / ".mozilla" / "firefox").mkdir(parents=True)

    assert detect_browsers(home=tmp_path, platform="linux") == ["firefox", "chromium"]


def test_detect_browsers_darwin_paths_and_safari(tmp_path: Path) -> None:
    (tmp_path / "Library" / "Application Support" / "Firefox").mkdir(parents=True)
    (tmp_path / "Library" / "Containers" / "com.apple.Safari").mkdir(parents=True)

    assert detect_browsers(home=tmp_path, platform="darwin") == ["firefox", "safari"]
    assert detect_browsers(home=tmp_path, platform="linux") == []


def test_detect_browsers_empty_when_no_profiles(tmp_path: Path) -> None:
    assert detect_browsers(home=tmp_path, platform="linux") == []


def test_cookie_header_from_netscape_filters_youtube_domains(tmp_path: Path) -> None:
    path = _write_cookies(tmp_path / "cookies.txt")

    header = cookie_header_from_netscape(path)

    assert "SAPISID=sap-value" in header
    assert "__Secure-3PSID=session-value" in header
    assert "OTHER" not in header


def test_cookie_header_from_netscape_rejects_lookalike_domains(tmp_path: Path) -> None:
    content = (
        "# Netscape HTTP Cookie File\n"
        ".notyoutube.com\tTRUE\t/\tTRUE\t0\t__Secure-3PAPISID\tevil\n"
        ".youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-3PAPISID\treal\n"
        "music.youtube.com\tFALSE\t/\tTRUE\t0\tSAPISID\treal\n"
    )
    path = _write_cookies(tmp_path / "cookies.txt", content)

    header = cookie_header_from_netscape(path)

    assert "__Secure-3PAPISID=real" in header
    assert "evil" not in header


def test_cookie_header_from_netscape_requires_sapisid(tmp_path: Path) -> None:
    content = (
        "# Netscape HTTP Cookie File\n"
        ".youtube.com\tTRUE\t/\tTRUE\t0\tVISITOR_INFO1_LIVE\tx\n"
    )
    path = _write_cookies(tmp_path / "cookies.txt", content)

    with pytest.raises(ConfigError, match="SAPISID cookie missing"):
        cookie_header_from_netscape(path)


def test_cookie_header_from_netscape_rejects_garbage(tmp_path: Path) -> None:
    path = _write_cookies(tmp_path / "cookies.txt", "not a cookie file\n")

    with pytest.raises(ConfigError, match="not a readable Netscape"):
        cookie_header_from_netscape(path)


def _fake_run_writing(content: str | None, stderr: str = ""):
    def fake_run(command, **kwargs):
        cookies_path = Path(command[command.index("--cookies") + 1])
        if content is not None:
            cookies_path.write_text(content, encoding="utf-8")
        return subprocess.CompletedProcess(
            command, returncode=2, stdout="", stderr=stderr
        )

    return fake_run


def test_export_browser_cookie_header_success(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("bester_ytm.auth_capture.shutil.which", lambda name: "/usr/bin/yt-dlp")
    monkeypatch.setattr(
        "bester_ytm.auth_capture.subprocess.run",
        _fake_run_writing(
            NETSCAPE_COOKIES,
            stderr="yt-dlp: error: You must provide at least one URL.\n",
        ),
    )
    private_dir = tmp_path / "bester-ytm"

    header = export_browser_cookie_header("firefox", private_dir)

    assert "SAPISID=sap-value" in header
    assert stat.S_IMODE(private_dir.stat().st_mode) == 0o700
    assert list(private_dir.glob("cookies-*")) == []


def test_export_browser_cookie_header_reports_ytdlp_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("bester_ytm.auth_capture.shutil.which", lambda name: "/usr/bin/yt-dlp")
    monkeypatch.setattr(
        "bester_ytm.auth_capture.subprocess.run",
        _fake_run_writing(
            None,
            stderr=(
                "ERROR: could not find chrome cookies database\n"
                "yt-dlp: error: You must provide at least one URL.\n"
            ),
        ),
    )

    with pytest.raises(ConfigError, match="could not find chrome cookies database"):
        export_browser_cookie_header("chrome", tmp_path / "bester-ytm")
    assert list((tmp_path / "bester-ytm").glob("cookies-*")) == []


def test_export_browser_cookie_header_requires_ytdlp(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr("bester_ytm.auth_capture.shutil.which", lambda name: None)

    with pytest.raises(ConfigError, match="yt-dlp is not installed"):
        export_browser_cookie_header("firefox", tmp_path / "bester-ytm")


def test_headers_from_paste_parses_firefox_single_line_curl() -> None:
    pasted = (
        "curl 'https://music.youtube.com/youtubei/v1/browse?prettyPrint=false' "
        "--compressed -X POST -H 'User-Agent: Mozilla/5.0' "
        "-H 'cookie: __Secure-3PAPISID=sap; __Secure-3PSID=sid' "
        "-H 'x-goog-authuser: 0' -H 'authorization: SAPISIDHASH 12_ab'"
    )

    headers_raw = headers_from_paste(pasted)

    assert "cookie: __Secure-3PAPISID=sap; __Secure-3PSID=sid" in headers_raw
    assert "x-goog-authuser: 0" in headers_raw
    assert "https://music.youtube.com" not in headers_raw.splitlines()[0]


def test_headers_from_paste_parses_chrome_multiline_curl() -> None:
    pasted = (
        "curl 'https://music.youtube.com/youtubei/v1/browse' \\\n"
        "  -H 'accept: */*' \\\n"
        "  -b '__Secure-3PAPISID=sap; SAPISID=sap' \\\n"
        "  -H 'x-goog-authuser: 0' \\\n"
        "  --data-raw '{}'"
    )

    headers_raw = headers_from_paste(pasted)

    assert "cookie: __Secure-3PAPISID=sap; SAPISID=sap" in headers_raw
    assert "accept: */*" in headers_raw


def test_headers_from_paste_rejects_curl_without_cookie() -> None:
    with pytest.raises(ConfigError, match="no cookie header"):
        headers_from_paste("curl 'https://music.youtube.com' -H 'accept: */*'")


def test_headers_from_paste_rejects_copy_as_fetch() -> None:
    pasted = 'fetch("https://music.youtube.com/youtubei/v1/browse", {"headers": {}})'

    with pytest.raises(ConfigError, match="Copy as cURL"):
        headers_from_paste(pasted)


def test_headers_from_paste_keeps_raw_header_block() -> None:
    raw = "accept: */*\ncookie: SAPISID=y\nx-goog-authuser: 0"

    assert headers_from_paste(raw) == raw


def test_headers_from_paste_normalizes_bracketed_nel_paste() -> None:
    raw = "accept: */*\u0085cookie: SAPISID=y"
    pasted = "\x1b[200~" + raw + "\x1b[201~"

    assert headers_from_paste(pasted) == "accept: */*\ncookie: SAPISID=y"


def test_ensure_required_headers_synthesizes_missing_lines() -> None:
    headers_raw = ensure_required_headers("cookie: __Secure-3PAPISID=sap-value")

    lines = dict(line.split(": ", 1) for line in headers_raw.splitlines())
    assert lines["x-goog-authuser"] == "0"
    assert lines["origin"] == "https://music.youtube.com"
    assert lines["authorization"].startswith("SAPISIDHASH ")


def test_ensure_required_headers_keeps_existing_lines() -> None:
    raw = (
        "cookie: __Secure-3PAPISID=sap\n"
        "x-goog-authuser: 1\n"
        "authorization: SAPISIDHASH 12_ab\n"
        "x-origin: https://music.youtube.com"
    )

    assert ensure_required_headers(raw) == raw


def test_ensure_required_headers_rejects_cookie_without_sapisid() -> None:
    with pytest.raises(ConfigError, match="no SAPISID value"):
        ensure_required_headers("cookie: VISITOR_INFO1_LIVE=x")


def test_build_headers_raw_feeds_ytmusicapi_setup() -> None:
    from ytmusicapi import setup as ytmusicapi_setup

    headers_raw = build_headers_raw("__Secure-3PAPISID=sap; __Secure-3PSID=sid")
    saved = json.loads(ytmusicapi_setup(headers_raw=headers_raw))

    assert saved["cookie"] == "__Secure-3PAPISID=sap; __Secure-3PSID=sid"
    assert saved["x-goog-authuser"] == "0"
    assert "SAPISIDHASH" in saved["authorization"]
